config/routes.rb
Rails.application.routes.draw do
  resources :songs

  resources :users, only: [:new, :create, :show]

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

end

app/models/song.rb
class Song < ActiveRecord::Base
  validates :title, presence: true

  # def to_param
  #   title
  # end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by(username: params[:session][:username])
    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      flash[:message] = "Welcome #{ @user.username }"
      redirect_to @user
    else
      redirect_to login_path
      flash[:errors] = "Invalid information"
      # sad path - either user doesn't exist, or password is incorrect
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:message] = "logged out"
    redirect_to login_path
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_song, only: [:show, :edit, :update, :destroy]

  def index
    @songs = Song.all
    session[:most_recent_song_title] = Song.last.title
  end

  def show
  end

  def new
    @song = Song.new
  end

  def create
    # Song.create song_params

    # @song = Song.new
    # if song.save
    #   ...
    # end


    @song = Song.new(song_params)


    if @song.save
      flash[:notice] = "You successfully created a song"
    else
      flash[:error] = @song.errors.full_messages.first
    end

    redirect_to songs_path
  end

  def edit
  end

  def update
    @song.update(song_params)

    redirect_to songs_path
  end

  def destroy
    @song.destroy

    redirect_to songs_path
  end

  private

  def song_params
    params.require(:song).permit(:title, :artist)
  end

  def set_song
    @song = Song.find(params[:id])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "Welcome #{ @user.username }"
      redirect_to @user
    else
      redirect_to login_path
      flash[:error] = "Invalid information"
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyJams</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div>
  <% if current_user %>
      Hello, <%= current_user.username %>
      <%= link_to "Logout", logout_path, method: :delete %>
  <% end %>
</div>

<% flash.each do |type, msg| %>
    <%= content_tag :div, msg, class: "flash_#{type}" %>
<% end %>

<%= yield %>

</body>
</html>

app/views/songs/_form.html.erb
<%= form_for(@song) do |f| %>
    <%= f.label :title %>
    <%= f.text_field :title %> <br>

    <%= f.label :artist %>
    <%= f.text_field :artist %> <br>
    <%= f.submit %>
<% end %>

app/views/songs/edit.html.erb
<%= link_to "All Songs", songs_path %>

<h1>Edit Song</h1>

<%= render 'form' %>

<%#= song_path %>

<%= link_to "delete", song_path, method: :delete %>

app/views/songs/index.html.erb
<h1>All Songs</h1>

<% @songs.each do |song| %>
"<%= link_to song.title, song %>"
    <%= link_to "edit", edit_song_path(song) %>
    <%= link_to "delete", song_path(song), method: :delete %>
    <br>
<% end %><br>

<%= link_to "New Song", new_song_path %>

app/views/songs/new.html.erb
<%= link_to "All Songs", songs_path %>

<h1>New Song</h1>

<%= render 'form' %>

app/views/songs/show.html.erb
<%= link_to "All Songs", songs_path %>

<h1><%= @song.title %></h1>
<p><%= @song.artist %></p>

<%= link_to "edit", edit_song_path %>
<%= link_to "delete", song_path, method: :delete, data: { confirm: "Are you sure"} %>

app/views/users/new.html.erb
<h1>Enter New User Info:</h1>

<%= form_for(@user) do |f| %>
    <%= f.label :username %>
    <%= f.text_field :username %> <br>

    <%= f.label :password %>
    <%= f.password_field :password %>

    <%= f.submit "Create Account" %>
<% end %>

app/views/users/show.html.erb
<p>
  <strong>Newest song:</strong> <%= session[:most_recent_song_title] %>
</p>